# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.cache/wt [current_project]
set_property parent.project_path /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/new/FSM.v
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/Spectre_Servo.srcs/PWM_M.v
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/Accel.srcs/accel.v
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/new/SPECTRE_MK0.v
}
read_vhdl -library xil_defaultlib {
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/Accel.srcs/ADXL362Ctrl.vhd
  /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/sources_1/Accel.srcs/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/constrs_1/imports/CEC330/Nexys-A7-100T-Master-Template.xdc
set_property used_in_implementation false [get_files /home/milesosborne/projects/CEC330/Spectre_MK0/Spectre_MK0.srcs/constrs_1/imports/CEC330/Nexys-A7-100T-Master-Template.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SPECTRE_MK0 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SPECTRE_MK0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SPECTRE_MK0_utilization_synth.rpt -pb SPECTRE_MK0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
